### ISSUE TITLE
Error when loading ver 1.1.1

### ISSUE THREAD

**Issue by Feuraver** [TeamAOF/All-of-Fabric-5#214]
Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config stepheightentityattribute.mixins.json for mod step-height-entity-attribute
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config stepheightentityattribute.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'stepheightentityattribute.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 6 more

**Comment by ImAK9** [comment]
Update pack
