### ISSUE TITLE
Error setting up server (kotlin)

### ISSUE THREAD

**Issue by JadeiteSwan** [TeamAOF/All-of-Fabric-5#231]
Not exactly an expert at setting up servers, but every time I try to set it up, it gives an error after confirming EULA. Any help would be appreciated. (Sorry in advance if this is the wrong place to ask)

kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
at atm.bloodworkxgaming.serverstarter.LoaderManager.startServer(LoaderManager.kt:169)
at atm.bloodworkxgaming.serverstarter.LoaderManager.handleServer(LoaderManager.kt:43)
at atm.bloodworkxgaming.serverstarter.ServerStarter.startLoading(ServerStarter.kt:190)
at atm.bloodworkxgaming.serverstarter.ServerStarterKt.main(ServerStarter.kt:202)

**Comment by Yoosk** [comment]
Which modpack is that, which version of the pack, and it seems like you edited/corrupted config for serverstarter.

**Comment by JadeiteSwan** [comment]
1.1.4. Haven't edited anything.
