### ISSUE TITLE
Complete freeze of all enteties, presumably 0tps error

### ISSUE THREAD

**Issue by viker17** [TeamAOF/All-of-Fabric-5#273]
Whenever I try to load just a few chunks, the game completly freezes for all players making it impossible to interact with anything.
What I've been doing is just closing the game with task manager as closing the game normally only makes it freeze on the saving world screen.

I'm happy to share any logs if possible, but I don't have any server logs as the "server" is a purely lan server.

**Comment by dandin87** [comment]
Is this an updated world or a new world? Even though its Lan, I would recommend running a local server. It would perform better this way even if you are running it on the same computer as your client. You would need about 12-16GB RAM in your PC, so that you could run the server and client at 4GB each and have enough for the OS.

It can be a little tricky to get Player data from a lan world to the server correctly is why I ask if its a new world. But best way is to have players place on their items in a chest so you don't have to copy the player data. You simply take the save folder and rename it world and put it in the folder with the extracted serverpack zip, then run the .bat file.

**Comment by viker17** [comment]
It is a new world, created no much later than 2 days ago, and I too did try and create a server, but there I am met with an entirely different error during the setup, though this one I can actually record and send on for you.

The error occurs when I run the startserver.bat provided in the server files available through the curseforge launcher ofr AOF 5 specifically.
---error message below---

Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:68)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66)
Caused by: java.lang.RuntimeException: Error invoking MC server bundler: java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at net.fabricmc.loader.impl.game.minecraft.BundlerProcessor.process(BundlerProcessor.java:103)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:187)
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:172)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:125)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	... 5 more
Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.BundlerProcessor$1.loadClass(BundlerProcessor.java:66)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.BundlerProcessor.process(BundlerProcessor.java:86)
	... 10 more

**Comment by dandin87** [comment]
Although your Minecraft Launcher is using Java17, it is one that is not installed in the OS, so when you run the server files they are looking for an installed Java 17 which does not exist. You will need to install Java 17.
https://adoptium.net/download

**Comment by viker17** [comment]
This worked! Yet, the server is 1.18.2 where the Mincraft version AOF5 seems to be using is 1.18.1...

**Comment by dandin87** [comment]
If Curseforge launcher you can right click the pack and select versions or something like that to change the version to 1.2.0

**Comment by viker17** [comment]
Yeah that's what me and a friend of mine assumed as well, but there is only the "current" release, then beta and alpha, but neither beta or alpha gerners any result...

**Comment by viker17** [comment]
okay so, i have a server up and running, albeit still using the 1.15 version of AOF5,,,, still getting the error7bug of total inability to interact with anything...
