### ISSUE TITLE
[ERROR] Error while trying to get URL from cursemeta for mod  (1.2.2 server)

### ISSUE THREAD

**Issue by DesolatePsyche** [TeamAOF/All-of-Fabric-5#283]
Grabbed the 1.2.2 server files. So I'm launching fresh server in empty folder. Console is essentially spamming this with every mod I'm guessing? As I notice that every time that error shows up, mentioned ID is different.

i.e
"java.io.IOException: Request to https://cursemeta.dries007.net/372124/3573395.json was not successful.
        at atm.bloodworkxgaming.serverstarter.packtype.curse.CursePackType$downloadMods$1.accept(CursePackType.kt:202)
        at atm.bloodworkxgaming.serverstarter.packtype.curse.CursePackType$downloadMods$1.accept(CursePackType.kt:26)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[21:41:42] [ERROR] Error while trying to get URL from cursemeta for mod ModEntryRaw(projectID=420709, fileID=3772450)"

**Comment by dandin87** [comment]
Just copy the mods from the client folder, and then delete the world folder as it would have made a vanilla world first time. Curseforge API changes broke mod downloading

**Comment by DesolatePsyche** [comment]
> Just copy the mods from the client folder, and then delete the world folder as it would have made a vanilla world first time. Curseforge API changes broke mod downloading

I see. Cheers, could run server now.
